name: OAuth2 JWT password
values:
  - key: ashost
    value: 'http://localhost:8081'
  - key: rshost
    value: 'http://localhost:8080'
  - key: client-id
    value: myclientid
  - key: client-secret
    value: myclientsecret
  - key: username
    value: alex@gmail.com
  - key: password
    value: '123456'
  - key: token
    secret: true
